import uuid
from datetime import datetime

from sqlalchemy import DateTime, ForeignKey, Integer, Text, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class Feedback(Base):
    """
    Post-session feedback report generated by GPT-4o.
    Structured scores stored as JSONB for flexibility — the rubric
    may evolve without needing migrations.
    """
    __tablename__ = 'feedback'

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    session_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey('sessions.id'), nullable=False, unique=True
    )
    # unique=True: one feedback report per session

    overall_score: Mapped[int | None] = mapped_column(Integer, nullable=True)  # 1-10

    # JSONB fields — flexible structure, queryable in PostgreSQL
    # e.g. {"communication": 7, "technical_accuracy": 8, "structure": 6}
    category_scores: Mapped[dict | None] = mapped_column(JSONB, nullable=True)

    # e.g. ["Clear explanation of DCF methodology", "Good deal walkthrough"]
    strengths: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    weaknesses: Mapped[list | None] = mapped_column(JSONB, nullable=True)
    recommendations: Mapped[list | None] = mapped_column(JSONB, nullable=True)

    summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )
