#
# Copyright (c) 2024–2025, Daily
#
# SPDX-License-Identifier: BSD 2-Clause License
#

"""cv_screener - Pipecat Voice Agent

This bot uses a cascade pipeline: Speech-to-Text → LLM → Text-to-Speech

Generated by Pipecat CLI

Required AI services:
- Deepgram (Speech-to-Text)
- Openai (LLM)
- Cartesia (Text-to-Speech)

Run the bot using::

    uv run bot.py
"""

import os

from dotenv import load_dotenv
import httpx
from loguru import logger
from pipecat.audio.vad.silero import SileroVADAnalyzer
from pipecat.frames.frames import LLMRunFrame
from pipecat.pipeline.pipeline import Pipeline
from pipecat.pipeline.runner import PipelineRunner
from pipecat.pipeline.task import PipelineParams, PipelineTask
from pipecat.processors.aggregators.llm_context import LLMContext
from pipecat.processors.aggregators.llm_response_universal import (
    AssistantTurnStoppedMessage,
    LLMContextAggregatorPair,
    LLMUserAggregatorParams,
    UserTurnStoppedMessage,
)
from pipecat.runner.types import DailyRunnerArguments, RunnerArguments, SmallWebRTCRunnerArguments
from pipecat.services.cartesia.tts import CartesiaTTSService
from pipecat.services.deepgram.stt import DeepgramSTTService
from pipecat.services.openai.llm import OpenAILLMService
from pipecat.transports.base_transport import BaseTransport, TransportParams
from pipecat.transports.daily.transport import DailyParams, DailyTransport
from pipecat.transports.smallwebrtc.connection import SmallWebRTCConnection
from pipecat.transports.smallwebrtc.transport import SmallWebRTCTransport
from pipecat.audio.vad.vad_analyzer import VADParams

load_dotenv(override=True)


async def run_bot(transport: BaseTransport, body: dict):
    """Main bot logic."""
    logger.info(f"Starting bot with config: {body}")
    
    # Extract session config
    system_prompt = body.get("system_prompt", "You are a helpful assistant.")
    language = body.get("language", "english")
    user_name = body.get("user_name", "Candidate")
    duration = body.get("duration_minutes", 30)
    session_id = body.get("session_id")
    backend_url = body.get("backend_url")  # your FastAPI URL for posting transcripts

    # Speech-to-Text service
    stt = DeepgramSTTService(api_key=os.getenv("DEEPGRAM_API_KEY"))

    # Text-to-Speech service
    voice_map = {
        "english": os.getenv("CARTESIA_VOICE_ID_EN"),
        "german": os.getenv("CARTESIA_VOICE_ID_DE"),
        "spanish": os.getenv("CARTESIA_VOICE_ID_ES"),
        "italian": os.getenv("CARTESIA_VOICE_ID_IT"),
        "dutch": os.getenv("CARTESIA_VOICE_ID_NL"),
    }
    
    tts = CartesiaTTSService(
        api_key=os.getenv("CARTESIA_API_KEY"),
        settings=CartesiaTTSService.Settings(
            voice=voice_map.get(language, os.getenv("CARTESIA_VOICE_ID_EN")),
        ),
    )

    # LLM service
    llm = OpenAILLMService(
        api_key=os.getenv("OPENAI_API_KEY"),
        settings=OpenAILLMService.Settings(
            model=os.getenv("OPENAI_MODEL"),
            system_instruction=system_prompt
        ),
    )

    context = LLMContext()
    user_aggregator, assistant_aggregator = LLMContextAggregatorPair(
        context,
        user_params=LLMUserAggregatorParams(
          vad_analyzer=SileroVADAnalyzer(params=VADParams(
              stop_secs=0.8,   # wait longer — candidates pause to think
              confidence=0.7,
          )),
        ),
    )

    # Pipeline - assembled from reusable components
    pipeline = Pipeline(
        [
            transport.input(),
            stt,
            user_aggregator,
            llm,
            tts,
            transport.output(),
            assistant_aggregator,
        ]
    )

    task = PipelineTask(
        pipeline,
        params=PipelineParams(
            enable_metrics=True,
            enable_usage_metrics=True,
        ),
        observers=[],
    )

    @task.rtvi.event_handler("on_client_ready")
    async def on_client_ready(rtvi):
        # Kick off the conversation
        context.add_message({"role": "user", "content": "The candidate has joined. Begin the interview."})
        await task.queue_frames([LLMRunFrame()])

    @transport.event_handler("on_client_connected")
    async def on_client_connected(transport, client):
        logger.info("Client connected")

    @transport.event_handler("on_client_disconnected")
    async def on_client_disconnected(transport, client):
        logger.info("Client disconnected")
        await task.cancel()

    service_key = body.get("service_api_key", "")
    @user_aggregator.event_handler("on_user_turn_stopped")
    async def on_user_turn_stopped(aggregator, strategy, message: UserTurnStoppedMessage):
        logger.info(f"Transcript: user: {message.content}")
        if session_id and backend_url:
            try:
                async with httpx.AsyncClient() as client:
                    await client.post(
                        f"{backend_url}/api/v1/transcripts", 
                        json={
                            "session_id": session_id,
                            "role": "user",
                            "content": message.content,
                        },
                        headers={"X-Service-Key": service_key},
                    )
            except Exception as e:
                logger.error(f"Failed to save transcript: {e}")

    @assistant_aggregator.event_handler("on_assistant_turn_stopped")
    async def on_assistant_turn_stopped(aggregator, message: AssistantTurnStoppedMessage):
        logger.info(f"Transcript: assistant: {message.content}")
        if session_id and backend_url:
            try:
                async with httpx.AsyncClient() as client:
                    await client.post(
                        f"{backend_url}/api/v1/transcripts", 
                        json={
                            "session_id": session_id,
                            "role": "assistant",
                            "content": message.content,
                        },
                        headers={"X-Service-Key": service_key},
                    )
            except Exception as e:
                logger.error(f"Failed to save transcript: {e}")

    runner = PipelineRunner(handle_sigint=False)

    await runner.run(task)


async def bot(runner_args: RunnerArguments):
    """Main bot entry point."""
    # Extract custom session data passed by your FastAPI backend
    body = runner_args.body or {}
    
    # Krisp is available when deployed to Pipecat Cloud
    if os.environ.get("ENV") != "local":
        from pipecat.audio.filters.krisp_viva_filter import KrispVivaFilter

        krisp_filter = KrispVivaFilter()
    else:
        krisp_filter = None

    transport = None

    match runner_args:
        case DailyRunnerArguments():
            transport = DailyTransport(
                runner_args.room_url,
                runner_args.token,
                "Pipecat Bot",
                params=DailyParams(
                    audio_in_enabled=True,
                    audio_in_filter=krisp_filter,
                    audio_out_enabled=True,
                ),
            )
        case SmallWebRTCRunnerArguments():
            webrtc_connection: SmallWebRTCConnection = runner_args.webrtc_connection

            transport = SmallWebRTCTransport(
                webrtc_connection=webrtc_connection,
                params=TransportParams(
                    audio_in_enabled=True,
                    audio_in_filter=krisp_filter,
                    audio_out_enabled=True,
                ),
            )
        case _:
            logger.error(f"Unsupported runner arguments type: {type(runner_args)}")
            return

    await run_bot(transport, body)


if __name__ == "__main__":
    from pipecat.runner.run import main

    main()
