"""Added email verification and password reset to user model

Revision ID: 3de37d4e09d0
Revises: 91c8248d326a
Create Date: 2026-04-06 12:49:14.767114

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3de37d4e09d0'
down_revision: Union[str, Sequence[str], None] = '91c8248d326a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('verification_token', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'users', sa.Column('password_reset_token', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'users',
        sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
