"""unsubscribe token

Revision ID: aed33fe7b736
Revises: 676b2103145e
Create Date: 2026-04-20 13:45:46.879536

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aed33fe7b736'
down_revision: Union[str, Sequence[str], None] = '676b2103145e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist', sa.Column('unsubscribe_token', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'waitlist', ['unsubscribe_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist', type_='unique')
    op.drop_column('waitlist', 'unsubscribe_token')
    # ### end Alembic commands ###
